# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

n_zeros_dense_mat <- function(mat) {
    .Call(`_SeuratIntegrate_n_zeros_dense_mat`, mat)
}

n_zeros_sparse_mat <- function(mat) {
    .Call(`_SeuratIntegrate_n_zeros_sparse_mat`, mat)
}

